// Auto-generated by LogicModelGenerator.py — DO NOT EDIT
#pragma once
#include <cstdint>
namespace Logic_BitwiseNot_Input {
   static int32_t data_a[24] = {-27, 93, -18, -35, 81, -26, -85, -7, 59, -63, -8, -75, 37, -5, -34, -55, 12, 33, 88, -13, -68, 66, 25, 40};
} // namespace Logic_BitwiseNot_Input
