// Auto-generated by LogicModelGenerator.py — DO NOT EDIT
#pragma once
#include <cstdint>
namespace Logic_BitwiseXor_Input {
   static int32_t data_a[15] = {-82, 10, 77, -88, 71, 65, -45, 26, -67, 51, 40, -30, -87, 94, -11};
   static int32_t data_b[15] = {78, 35, 55, 51, -62, -28, -7, -1, -92, 9, -70, 48, 36, 84, 48};
} // namespace Logic_BitwiseXor_Input
