// Auto-generated by LogicModelGenerator.py — DO NOT EDIT
#pragma once
#include <cstdint>
namespace Logic_Xor_Input {
   static uint8_t data_a[16] = {0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1};
   static uint8_t data_b[16] = {1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0};
} // namespace Logic_Xor_Input
