// Auto-generated by ReduceMaxModelGenerator.py — DO NOT EDIT
#pragma once
namespace ReduceMax_ExpectedOutput {
   static float output[3] = {5.00000000f, 5.00000000f, 4.00000000f};
} // namespace ReduceMax_ExpectedOutput
