// Auto-generated by ReduceMaxModelGenerator.py — DO NOT EDIT
#pragma once
namespace ReduceMax_axis0_ExpectedOutput {
   static float output[4] = {0.30471709f, -0.85304391f, 0.87939799f, 0.94056469f};
} // namespace ReduceMax_axis0_ExpectedOutput
