// Auto-generated by TriluModelGenerator.py — DO NOT EDIT
#pragma once
namespace Trilu_upper_Input {
   static float data[16] = {0.30471709f, -1.03998411f, 0.75045121f, 0.94056469f, -1.95103514f, -1.30217946f, 0.12784040f, -0.31624261f, -0.01680116f, -0.85304391f, 0.87939799f, 0.77779192f, 0.06603070f, 1.12724125f, 0.46750933f, -0.85929245f};
} // namespace Trilu_upper_Input
