// Auto-generated by TriluModelGenerator.py — DO NOT EDIT
#pragma once
namespace Trilu_kn1_Input {
   static float data[15] = {0.22359554f, 0.67891353f, 0.06757907f, 0.28911939f, 0.63128823f, -1.45715582f, -0.31967121f, -0.47037265f, -0.63887787f, -0.27514225f, 1.49494135f, -0.86583114f, 0.96827835f, -1.68286979f, -0.33488503f};
} // namespace Trilu_kn1_Input
