// Auto-generated by LogicModelGenerator.py — DO NOT EDIT
#pragma once
#include <cstdint>
namespace Logic_BitwiseOr_ExpectedOutput {
   static int32_t outputs[15] = {-18, 43, 127, -69, -57, -27, -5, -1, -67, 59, -70, -14, -83, 94, -11};
} // namespace Logic_BitwiseOr_ExpectedOutput
