// Auto-generated by LogicModelGenerator.py — DO NOT EDIT
#pragma once
#include <cstdint>
namespace Logic_Xor_ExpectedOutput {
   static uint8_t outputs[16] = {1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1};
} // namespace Logic_Xor_ExpectedOutput
