// Auto-generated by LogicModelGenerator.py — DO NOT EDIT
#pragma once
#include <cstdint>
namespace Logic_BitwiseNot_ExpectedOutput {
   static int32_t outputs[24] = {26, -94, 17, 34, -82, 25, 84, 6, -60, 62, 7, 74, -38, 4, 33, 54, -13, -34, -89, 12, 67, -67, -26, -41};
} // namespace Logic_BitwiseNot_ExpectedOutput
