// Auto-generated by LogicModelGenerator.py — DO NOT EDIT
#pragma once
#include <cstdint>
namespace Logic_BitwiseXor_ExpectedOutput {
   static int32_t outputs[15] = {-32, 41, 122, -101, -123, -91, 42, -27, 25, 58, -110, -46, -115, 10, -59};
} // namespace Logic_BitwiseXor_ExpectedOutput
