// Auto-generated by LogicModelGenerator.py — DO NOT EDIT
#pragma once
#include <cstdint>
namespace Logic_BitwiseAnd_ExpectedOutput {
   static int32_t outputs[15] = {14, 2, 5, 32, 66, 64, -47, 26, -92, 1, 40, 32, 32, 84, 48};
} // namespace Logic_BitwiseAnd_ExpectedOutput
