// Auto-generated by LogicModelGenerator.py — DO NOT EDIT
#pragma once
#include <cstdint>
namespace Logic_And_ExpectedOutput {
   static uint8_t outputs[16] = {0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0};
} // namespace Logic_And_ExpectedOutput
