// Auto-generated by ReduceMaxModelGenerator.py — DO NOT EDIT
#pragma once
namespace ReduceMax_mid_ExpectedOutput {
   static float output[8] = {0.36875078f, 1.12724125f, 1.22254133f, -0.04992591f, 0.41273260f, 0.43082100f, 2.14164758f, 1.12897229f};
} // namespace ReduceMax_mid_ExpectedOutput
