#!/usr/bin/env python3
"""
Generate ONNX test models for the SOFIE ReduceMax operator and write
the corresponding C++ reference headers.

Models created
──────────────
  ReduceMax.onnx            [1,2,3] float, axis=1, keepdims=0  (kLast / matches ReduceMean)
  ReduceMax_axis0.onnx      [3,4]   float, axis=0, keepdims=0  (kFirst)
  ReduceMax_mid.onnx        [2,3,4] float, axis=1, keepdims=0  (kMiddle)

Usage:
    cd <repo>/SOFIE/core/test/input_models
    python3 ReduceMaxModelGenerator.py
"""

import os
import numpy as np
import onnx
from onnx import helper, TensorProto

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
REF_DIR = os.path.join(OUT_DIR, "references")
os.makedirs(REF_DIR, exist_ok=True)


def make_reducemax_model(input_shape, axes, keepdims, name):
    """Build a single ReduceMax node model (opset 13, axes as attribute)."""
    x = helper.make_tensor_value_info("input", TensorProto.FLOAT, input_shape)
    # Compute output shape
    out_shape = list(input_shape)
    for ax in axes:
        if keepdims:
            out_shape[ax] = 1
        else:
            out_shape[ax] = None          # will be removed below
    if not keepdims:
        out_shape = [d for i, d in enumerate(out_shape) if i not in axes]
    y = helper.make_tensor_value_info("output", TensorProto.FLOAT, out_shape)

    node = helper.make_node(
        "ReduceMax",
        inputs=["input"],
        outputs=["output"],
        axes=axes,
        keepdims=keepdims,
    )
    graph = helper.make_graph([node], name, [x], [y])
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid("", 13)])
    model.ir_version = 7
    onnx.checker.check_model(model)
    return model


def ref_header(name, data):
    flat = data.flatten()
    vals = ", ".join(f"{v:.8f}f" for v in flat)
    return (
        f"// Auto-generated by ReduceMaxModelGenerator.py — DO NOT EDIT\n"
        f"#pragma once\n"
        f"namespace {name}_ExpectedOutput {{\n"
        f"   static float output[{flat.size}] = {{{vals}}};\n"
        f"}} // namespace {name}_ExpectedOutput\n"
    )


rng = np.random.default_rng(42)

CASES = [
    # (name,               input_shape,   axes,  keepdims,  input_data)
    # axis=1 on [1,2,3]  →  reduces last dim → kLast code path
    ("ReduceMax",          [1, 2, 3],     [1],   0,   np.array([[[5., 2., 3.], [5., 5., 4.]]], dtype=np.float32)),
    # axis=0 on [3,4]    →  reduces first dim → kFirst code path
    ("ReduceMax_axis0",    [3, 4],        [0],   0,   rng.standard_normal((3, 4)).astype(np.float32)),
    # axis=1 on [2,3,4]  →  reduces middle dim → kMiddle code path
    ("ReduceMax_mid",      [2, 3, 4],     [1],   0,   rng.standard_normal((2, 3, 4)).astype(np.float32)),
]

for (name, shape, axes, keepdims, x) in CASES:
    model = make_reducemax_model(shape, axes, keepdims, name)
    onnx_path = os.path.join(OUT_DIR, f"{name}.onnx")
    onnx.save(model, onnx_path)
    print(f"Saved {onnx_path}")

    y = np.max(x, axis=tuple(axes), keepdims=bool(keepdims))
    ref_path = os.path.join(REF_DIR, f"{name}.ref.hxx")
    with open(ref_path, "w") as f:
        f.write(ref_header(name, y))
    print(f"  → reference {ref_path}  shape={list(y.shape)}")

print("\nAll ReduceMax test models and references generated successfully.")
