#!/usr/bin/env python3
"""
Generate ONNX test models for the SOFIE Trilu operator and write
the corresponding C++ reference headers.

Models created
──────────────
  Trilu_upper.onnx         4×4 float, upper=1, k=0  (standard upper triangular)
  Trilu_lower.onnx         4×4 float, upper=0, k=0  (standard lower triangular)
  Trilu_k2.onnx            3×5 float, upper=1, k=2  (offset shifts diagonal up)
  Trilu_kn1.onnx           3×5 float, upper=0, k=-1 (offset shifts diagonal down)
  Trilu_3D.onnx            2×3×4 float, upper=1, k=0 (batched)

All k values are embedded as ONNX Constant nodes (scalar int64) so they are
resolved statically by SOFIE.

Usage:
    cd <repo>/SOFIE/core/test/input_models
    python3 TriluModelGenerator.py
"""

import os
import numpy as np
import onnx
from onnx import helper, TensorProto, numpy_helper

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
REF_DIR = os.path.join(OUT_DIR, "references")
os.makedirs(REF_DIR, exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def make_trilu_model(input_shape: list[int],
                     upper: int,
                     k: int,
                     name: str) -> onnx.ModelProto:
    """Build an ONNX model with a single Trilu node.

    k is embedded as a Constant node so SOFIE can resolve it statically.
    """
    # Graph inputs
    x = helper.make_tensor_value_info("input", TensorProto.FLOAT, input_shape)

    # Constant node for k
    k_const_name = "k_const"
    k_tensor = numpy_helper.from_array(np.array(k, dtype=np.int64),
                                        name=k_const_name)
    k_node = helper.make_node(
        "Constant",
        inputs=[],
        outputs=[k_const_name],
        value=k_tensor,
    )

    # Trilu node
    trilu_node = helper.make_node(
        "Trilu",
        inputs=["input", k_const_name],
        outputs=["output"],
        upper=upper,
    )

    # Graph output (shape same as input)
    y = helper.make_tensor_value_info("output", TensorProto.FLOAT, input_shape)

    graph = helper.make_graph(
        nodes=[k_node, trilu_node],
        name=name,
        inputs=[x],
        outputs=[y],
    )
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid("", 14)])
    model.ir_version = 7
    onnx.checker.check_model(model)
    return model


def ref_header(name: str, data: np.ndarray) -> str:
    """Emit a C++ header with the flattened expected output array."""
    flat = data.flatten()
    vals = ", ".join(f"{v:.8f}f" for v in flat)
    return (
        f"// Auto-generated by TriluModelGenerator.py — DO NOT EDIT\n"
        f"#pragma once\n"
        f"namespace {name}_ExpectedOutput {{\n"
        f"   static float outputs[{flat.size}] = {{{vals}}};\n"
        f"}} // namespace {name}_ExpectedOutput\n"
    )


def trilu_ref(x: np.ndarray, upper: int, k: int) -> np.ndarray:
    """NumPy reference implementation of the Trilu operator."""
    if upper:
        return np.triu(x, k=k).astype(np.float32)
    else:
        return np.tril(x, k=k).astype(np.float32)


# ─────────────────────────────────────────────────────────────────────────────
# Test cases
# ─────────────────────────────────────────────────────────────────────────────

rng = np.random.default_rng(42)

CASES = [
    # (name,               shape,       upper, k,  input_values)
    ("Trilu_upper",        [4, 4],      1,  0,  rng.standard_normal((4, 4)).astype(np.float32)),
    ("Trilu_lower",        [4, 4],      0,  0,  rng.standard_normal((4, 4)).astype(np.float32)),
    ("Trilu_k2",           [3, 5],      1,  2,  rng.standard_normal((3, 5)).astype(np.float32)),
    ("Trilu_kn1",          [3, 5],      0, -1,  rng.standard_normal((3, 5)).astype(np.float32)),
    ("Trilu_3D",           [2, 3, 4],   1,  0,  rng.standard_normal((2, 3, 4)).astype(np.float32)),
]

for (name, shape, upper, k, x) in CASES:
    # ── ONNX model ───────────────────────────────────────────────────────────
    model = make_trilu_model(shape, upper, k, name)
    onnx_path = os.path.join(OUT_DIR, f"{name}.onnx")
    onnx.save(model, onnx_path)
    print(f"Saved {onnx_path}")

    # ── Reference output ─────────────────────────────────────────────────────
    y = trilu_ref(x, upper, k)
    ref_path = os.path.join(REF_DIR, f"{name}.ref.hxx")
    with open(ref_path, "w") as f:
        f.write(ref_header(name, y))
    print(f"  → reference  {ref_path}  shape={list(y.shape)}")

    # Also save the input so tests can reconstruct it.
    inp_path = os.path.join(REF_DIR, f"{name}_input.ref.hxx")
    with open(inp_path, "w") as f:
        flat_in = x.flatten()
        vals_in = ", ".join(f"{v:.8f}f" for v in flat_in)
        f.write(
            f"// Auto-generated by TriluModelGenerator.py — DO NOT EDIT\n"
            f"#pragma once\n"
            f"namespace {name}_Input {{\n"
            f"   static float data[{flat_in.size}] = {{{vals_in}}};\n"
            f"}} // namespace {name}_Input\n"
        )
    print(f"  → input ref  {inp_path}")

print("\nAll Trilu test models and references generated successfully.")
