#!/usr/bin/env python3
"""
Generate ONNX test models for the SOFIE Logic operators and write
the corresponding C++ reference headers.

Models created
──────────────
  Logic_And.onnx          bool  input  4×4,   And
  Logic_Or.onnx           bool  input  4×4,   Or
  Logic_Xor.onnx          bool  input  4×4,   Xor
  Logic_BitwiseAnd.onnx   int32 input  3×5,   BitwiseAnd
  Logic_BitwiseOr.onnx    int32 input  3×5,   BitwiseOr
  Logic_BitwiseXor.onnx   int32 input  3×5,   BitwiseXor
  Logic_BitwiseNot.onnx   int32 input  2×3×4, BitwiseNot

Usage:
    cd <repo>/SOFIE/core/test/input_models
    python3 LogicModelGenerator.py
"""

import os
import numpy as np
import onnx
from onnx import helper, TensorProto, numpy_helper

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
REF_DIR = os.path.join(OUT_DIR, "references")
os.makedirs(REF_DIR, exist_ok=True)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def ref_header(name, data, dtype_str="bool"):
    """Emit a C++ header with the flattened expected output array."""
    flat = data.flatten()
    if dtype_str == "bool":
        # store as uint8 in C++
        vals = ", ".join(str(int(v)) for v in flat)
        arr_type = "uint8_t"
    else:
        # int32 / int64
        vals = ", ".join(str(int(v)) for v in flat)
        arr_type = dtype_str
    return (
        f"// Auto-generated by LogicModelGenerator.py — DO NOT EDIT\n"
        f"#pragma once\n"
        f"#include <cstdint>\n"
        f"namespace {name}_ExpectedOutput {{\n"
        f"   static {arr_type} outputs[{flat.size}] = {{{vals}}};\n"
        f"}} // namespace {name}_ExpectedOutput\n"
    )


def inp_header(name, data, dtype_str="bool"):
    """Emit a C++ header for the input data."""
    flat = data.flatten()
    if dtype_str == "bool":
        vals = ", ".join(str(int(v)) for v in flat)
        arr_type = "uint8_t"
    else:
        vals = ", ".join(str(int(v)) for v in flat)
        arr_type = dtype_str
    return (
        f"// Auto-generated by LogicModelGenerator.py — DO NOT EDIT\n"
        f"#pragma once\n"
        f"#include <cstdint>\n"
        f"namespace {name}_Input {{\n"
        f"   static {arr_type} data_a[{flat.size}] = {{{vals}}};\n"
        f"}} // namespace {name}_Input\n"
    )


def inp_header2(name, data_a, data_b, dtype_str="bool"):
    """Emit a C++ header with two input arrays (A and B)."""
    flat_a = data_a.flatten()
    flat_b = data_b.flatten()
    if dtype_str == "bool":
        arr_type = "uint8_t"
        vals_a = ", ".join(str(int(v)) for v in flat_a)
        vals_b = ", ".join(str(int(v)) for v in flat_b)
    else:
        arr_type = dtype_str
        vals_a = ", ".join(str(int(v)) for v in flat_a)
        vals_b = ", ".join(str(int(v)) for v in flat_b)
    return (
        f"// Auto-generated by LogicModelGenerator.py — DO NOT EDIT\n"
        f"#pragma once\n"
        f"#include <cstdint>\n"
        f"namespace {name}_Input {{\n"
        f"   static {arr_type} data_a[{flat_a.size}] = {{{vals_a}}};\n"
        f"   static {arr_type} data_b[{flat_b.size}] = {{{vals_b}}};\n"
        f"}} // namespace {name}_Input\n"
    )


# ─────────────────────────────────────────────────────────────────────────────
# Model builders
# ─────────────────────────────────────────────────────────────────────────────

def make_binary_model(op_name, shape, onnx_dtype, name):
    """Build a single-op binary model (A op B -> Y)."""
    type_map = {
        TensorProto.BOOL:  "bool",
        TensorProto.INT32: "int32",
        TensorProto.INT64: "int64",
    }
    a = helper.make_tensor_value_info("input_a", onnx_dtype, shape)
    b = helper.make_tensor_value_info("input_b", onnx_dtype, shape)
    y = helper.make_tensor_value_info("output",  onnx_dtype, shape)

    node = helper.make_node(op_name, inputs=["input_a", "input_b"], outputs=["output"])
    graph = helper.make_graph([node], name, [a, b], [y])
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid("", 18)])
    model.ir_version = 7
    onnx.checker.check_model(model)
    return model


def make_unary_model(op_name, shape, onnx_dtype, name):
    """Build a single-op unary model (X -> Y)."""
    x = helper.make_tensor_value_info("input", onnx_dtype, shape)
    y = helper.make_tensor_value_info("output", onnx_dtype, shape)

    node = helper.make_node(op_name, inputs=["input"], outputs=["output"])
    graph = helper.make_graph([node], name, [x], [y])
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid("", 18)])
    model.ir_version = 7
    onnx.checker.check_model(model)
    return model


# ─────────────────────────────────────────────────────────────────────────────
# Test cases
# ─────────────────────────────────────────────────────────────────────────────

rng = np.random.default_rng(42)

BOOL_SHAPE  = [4, 4]
INT_SHAPE   = [3, 5]
INT3D_SHAPE = [2, 3, 4]

# Bool inputs (stored as uint8 in SOFIE)
bool_a = rng.integers(0, 2, BOOL_SHAPE).astype(np.uint8)
bool_b = rng.integers(0, 2, BOOL_SHAPE).astype(np.uint8)

# Int32 inputs
int_a = rng.integers(-100, 100, INT_SHAPE, dtype=np.int32)
int_b = rng.integers(-100, 100, INT_SHAPE, dtype=np.int32)

int3d = rng.integers(-100, 100, INT3D_SHAPE, dtype=np.int32)

BINARY_CASES = [
    # (model_name, onnx_op, onnx_dtype, shape, a, b, ref, dtype_str)
    ("Logic_And",       "And",        TensorProto.BOOL,  BOOL_SHAPE,  bool_a, bool_b,
        np.logical_and(bool_a, bool_b).astype(np.uint8), "bool"),
    ("Logic_Or",        "Or",         TensorProto.BOOL,  BOOL_SHAPE,  bool_a, bool_b,
        np.logical_or(bool_a, bool_b).astype(np.uint8),  "bool"),
    ("Logic_Xor",       "Xor",        TensorProto.BOOL,  BOOL_SHAPE,  bool_a, bool_b,
        np.logical_xor(bool_a, bool_b).astype(np.uint8), "bool"),
    ("Logic_BitwiseAnd","BitwiseAnd", TensorProto.INT32, INT_SHAPE,   int_a,  int_b,
        (int_a & int_b).astype(np.int32), "int32_t"),
    ("Logic_BitwiseOr", "BitwiseOr",  TensorProto.INT32, INT_SHAPE,   int_a,  int_b,
        (int_a | int_b).astype(np.int32), "int32_t"),
    ("Logic_BitwiseXor","BitwiseXor", TensorProto.INT32, INT_SHAPE,   int_a,  int_b,
        (int_a ^ int_b).astype(np.int32), "int32_t"),
]

for (name, onnx_op, onnx_dtype, shape, a, b, ref, dtype_str) in BINARY_CASES:
    model = make_binary_model(onnx_op, shape, onnx_dtype, name)
    onnx_path = os.path.join(OUT_DIR, f"{name}.onnx")
    onnx.save(model, onnx_path)
    print(f"Saved {onnx_path}")

    ref_path = os.path.join(REF_DIR, f"{name}.ref.hxx")
    with open(ref_path, "w") as f:
        f.write(ref_header(name, ref, dtype_str))
    print(f"  → reference {ref_path}")

    inp_path = os.path.join(REF_DIR, f"{name}_input.ref.hxx")
    with open(inp_path, "w") as f:
        f.write(inp_header2(name, a, b, dtype_str))
    print(f"  → input ref {inp_path}")


# Unary BitwiseNot
name = "Logic_BitwiseNot"
model = make_unary_model("BitwiseNot", INT3D_SHAPE, TensorProto.INT32, name)
onnx_path = os.path.join(OUT_DIR, f"{name}.onnx")
onnx.save(model, onnx_path)
print(f"Saved {onnx_path}")

ref_not = (~int3d).astype(np.int32)
ref_path = os.path.join(REF_DIR, f"{name}.ref.hxx")
with open(ref_path, "w") as f:
    f.write(ref_header(name, ref_not, "int32_t"))
print(f"  → reference {ref_path}")

inp_path = os.path.join(REF_DIR, f"{name}_input.ref.hxx")
with open(inp_path, "w") as f:
    # Single-input version
    flat = int3d.flatten()
    vals = ", ".join(str(int(v)) for v in flat)
    content = (
        f"// Auto-generated by LogicModelGenerator.py — DO NOT EDIT\n"
        f"#pragma once\n"
        f"#include <cstdint>\n"
        f"namespace {name}_Input {{\n"
        f"   static int32_t data_a[{flat.size}] = {{{vals}}};\n"
        f"}} // namespace {name}_Input\n"
    )
    f.write(content)
print(f"  → input ref {inp_path}")

print("\nAll Logic test models and references generated successfully.")
