name: test-ci
on:
  push:
    branches:
      - test-ci

jobs:
  test-ci:
    runs-on: cern-nextgen-h100 
    container: registry.cern.ch/ngt/lxplus-like:9 
    steps:
      - name: nvidia-smi
        run: |
          nvidia-smi
